

spring:
    profiles:
        active: dev
    application:
        name: ilive-gateway
    redis:
        database: 0
        host: i.cn
   
server:
    port: 443
    ssl:
      key-store: /opt/keystore.p12
      key-store-password: 123456
      key-store-type: PKCS12
      key-alias: tomcat

    
eureka:
    client:
        serviceUrl:
            defaultZone: http://i.cn:1111/eureka

zuul:
    routes:
        b:
            path: /bbbbb/**
            serviceId: bservice
        c:
            path: /cc/**
            serviceId: c
        file:
            path: /file/**
            serviceId: a
        ilive:
            path: /ilive/**
            serviceId: izuanqian_ilive
        cfg:
            path: /cfg/**
            serviceId: izuanqian-cfg-server

api:
  auth:
    sign:
      salt: 401301823
    time: 600 # 10min
