## YAML Template.
---

#spring:
#    profiles:
#        active: dev
#    cloud:
#        config:
#            discovery:
#                enabled: true
#                serviceId: izuanqian-cfg-server
#            profile: dev
#            label: ${application.version}

server:
    port:  8888

application:
    version: 442