## YAML Template.
---

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ilive_res
        username: root
        password: root
    rabbitmq:
        host: i.cn
        port: 5672
        username: guest
        password: guest
    
